version: "3.9"
services:
  backend:
    build: .
    container_name: lemon-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev

  db:
    image: postgres:16
    container_name: lemon-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  node_modules:
